services:
  redis:
    image: redis:latest
    restart: always
    # ports:
    #   - "6379:6379"
    volumes:
      - ./redis/data:/data
    command: ["redis-server", "--save 60 1",  "--loglevel warning"]

  tcs_api_accessor:
    env_file:
      - TCSApiAccessor/.env
    build:
      context: TCSApiAccessor
    # ports:
    #   - "8000:8000"
    networks:
      - div_bot_network

  redis_accessor:
    build:
      context: RedisAccessor
    # ports:
    #   - "50051:50051"
    networks:
      - div_bot_network
    depends_on:
      - redis

  div_counter_manager:
    build:
      context: DivCounterManager
    ports:
      - "8000:8000"
    networks:
      - div_bot_network
    depends_on:
      - redis_accessor
      - tcs_api_accessor
#   db:
#     build:
#       context: db
#     networks:
#       - my_network

networks:
  div_bot_network:
    driver: bridge
