# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/api.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fproto/api.proto\x12\x07\x65xample\x1a\x1fgoogle/protobuf/timestamp.proto\"T\n\x12InstrumentsMessage\x12-\n\ttimestamp\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x0f\n\x07message\x18\x02 \x01(\t\"&\n\x13InstrumentsResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x07\n\x05\x45mpty\"\x1f\n\x0cListResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\" \n\rGetTickerData\x12\x0f\n\x07message\x18\x01 \x01(\t\"P\n\x0eTickerResponse\x12-\n\ttimestamp\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x0f\n\x07message\x18\x02 \x01(\t2b\n\x12InstrumentsService\x12L\n\x0fSaveInstruments\x12\x1b.example.InstrumentsMessage\x1a\x1c.example.InstrumentsResponse2E\n\x0bListService\x12\x36\n\x0bListRequest\x12\x0e.example.Empty\x1a\x15.example.ListResponse\"\x00\x32S\n\rTickerService\x12\x42\n\rTickerRequest\x12\x16.example.GetTickerData\x1a\x17.example.TickerResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.api_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INSTRUMENTSMESSAGE']._serialized_start=61
  _globals['_INSTRUMENTSMESSAGE']._serialized_end=145
  _globals['_INSTRUMENTSRESPONSE']._serialized_start=147
  _globals['_INSTRUMENTSRESPONSE']._serialized_end=185
  _globals['_EMPTY']._serialized_start=187
  _globals['_EMPTY']._serialized_end=194
  _globals['_LISTRESPONSE']._serialized_start=196
  _globals['_LISTRESPONSE']._serialized_end=227
  _globals['_GETTICKERDATA']._serialized_start=229
  _globals['_GETTICKERDATA']._serialized_end=261
  _globals['_TICKERRESPONSE']._serialized_start=263
  _globals['_TICKERRESPONSE']._serialized_end=343
  _globals['_INSTRUMENTSSERVICE']._serialized_start=345
  _globals['_INSTRUMENTSSERVICE']._serialized_end=443
  _globals['_LISTSERVICE']._serialized_start=445
  _globals['_LISTSERVICE']._serialized_end=514
  _globals['_TICKERSERVICE']._serialized_start=516
  _globals['_TICKERSERVICE']._serialized_end=599
# @@protoc_insertion_point(module_scope)
